/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apresentacao;

import entidades.contato.Contato;
import fachada.FachadaSistema;
import java.awt.CardLayout;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bruno
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }
    
    private void mostrarTela(String nomeTela){
        CardLayout card = (CardLayout)jPanelPrincipal.getLayout();
        card.show(jPanelPrincipal, nomeTela);
    }
    
    private void mostrarTelaEditar(String nomeTela){
        CardLayout card = (CardLayout)jPanelEditarContato.getLayout();
        card.show(jPanelEditarContato, nomeTela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("agenda?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        contatoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Contato c");
        contatoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contatoQuery.getResultList();
        contatoQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Contato c");
        contatoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contatoQuery1.getResultList();
        contatoQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Contato c");
        contatoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contatoQuery2.getResultList();
        contatoQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Contato c");
        contatoList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contatoQuery3.getResultList();
        jPanelMenuLateral = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanelBanner = new javax.swing.JPanel();
        jLabelBanner = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCadastrarContato = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tel_1 = new javax.swing.JTextField();
        tel_2 = new javax.swing.JTextField();
        tel_3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        observcoes = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jPanelEditarContato = new javax.swing.JPanel();
        jPanelExibirContatosBuscaEditar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListEditar = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanelEditarContatoSelecionado = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nomeEditar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tel_1Editar = new javax.swing.JTextField();
        tel_2Editar = new javax.swing.JTextField();
        tel_3Editar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        emailEditar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        observcoes1 = new javax.swing.JTextField();
        salvar1 = new javax.swing.JButton();
        jPanelListarContatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContatos = new javax.swing.JTable();
        jPanelExcluirContato = new javax.swing.JPanel();
        jPanelExibirContatosExcluir = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListExcluir = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelMenuLateral.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton2.setText("Cadastrar Contato");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Listar Contatos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Excluir Contato");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar Contato");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLateralLayout = new javax.swing.GroupLayout(jPanelMenuLateral);
        jPanelMenuLateral.setLayout(jPanelMenuLateralLayout);
        jPanelMenuLateralLayout.setHorizontalGroup(
            jPanelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLateralLayout.setVerticalGroup(
            jPanelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLateralLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanelBanner.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner_agenda.jpg"))); // NOI18N
        jLabelBanner.setText("jLabel1");

        javax.swing.GroupLayout jPanelBannerLayout = new javax.swing.GroupLayout(jPanelBanner);
        jPanelBanner.setLayout(jPanelBannerLayout);
        jPanelBannerLayout.setHorizontalGroup(
            jPanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBannerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanelBannerLayout.setVerticalGroup(
            jPanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBannerLayout.createSequentialGroup()
                .addComponent(jLabelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelCadastrarContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N

        jLabel2.setText("* Nome:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });

        jLabel3.setText("* Tel1:");

        jLabel4.setText("* Tel3:");

        jLabel5.setText("* Tel2:");

        jLabel6.setText("E-mail:");

        jLabel7.setText("Observações:");

        observcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observcoesActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrarContatoLayout = new javax.swing.GroupLayout(jPanelCadastrarContato);
        jPanelCadastrarContato.setLayout(jPanelCadastrarContatoLayout);
        jPanelCadastrarContatoLayout.setHorizontalGroup(
            jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarContatoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrarContatoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastrarContatoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastrarContatoLayout.createSequentialGroup()
                                .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel_3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanelCadastrarContatoLayout.setVerticalGroup(
            jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarContatoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastrarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(observcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar))
        );

        jPanelPrincipal.add(jPanelCadastrarContato, "cadastrarContato");

        jPanelEditarContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N
        jPanelEditarContato.setLayout(new java.awt.CardLayout());

        DefaultListModel listaEditar = new DefaultListModel();
        List<Contato> listaContatosEditar = FachadaSistema.getInstance().listarContatos();
        for(Contato contatoEditar: listaContatosEditar){
            listaEditar.addElement(contatoEditar.getNome());
        }
        jListEditar.setModel(listaEditar);
        jScrollPane3.setViewportView(jListEditar);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelExibirContatosBuscaEditarLayout = new javax.swing.GroupLayout(jPanelExibirContatosBuscaEditar);
        jPanelExibirContatosBuscaEditar.setLayout(jPanelExibirContatosBuscaEditarLayout);
        jPanelExibirContatosBuscaEditarLayout.setHorizontalGroup(
            jPanelExibirContatosBuscaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExibirContatosBuscaEditarLayout.createSequentialGroup()
                .addGap(0, 539, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelExibirContatosBuscaEditarLayout.setVerticalGroup(
            jPanelExibirContatosBuscaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirContatosBuscaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanelEditarContato.add(jPanelExibirContatosBuscaEditar, "exibirContatosEditar");

        jLabel10.setText("* Nome:");

        nomeEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEditarActionPerformed(evt);
            }
        });
        nomeEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeEditarFocusLost(evt);
            }
        });

        jLabel11.setText("* Tel1:");

        jLabel12.setText("* Tel3:");

        jLabel13.setText("* Tel2:");

        jLabel14.setText("E-mail:");

        jLabel15.setText("Observações:");

        observcoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observcoes1ActionPerformed(evt);
            }
        });

        salvar1.setText("Salvar");
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditarContatoSelecionadoLayout = new javax.swing.GroupLayout(jPanelEditarContatoSelecionado);
        jPanelEditarContatoSelecionado.setLayout(jPanelEditarContatoSelecionadoLayout);
        jPanelEditarContatoSelecionadoLayout.setHorizontalGroup(
            jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarContatoSelecionadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarContatoSelecionadoLayout.createSequentialGroup()
                        .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(emailEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditarContatoSelecionadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditarContatoSelecionadoLayout.createSequentialGroup()
                        .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(nomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEditarContatoSelecionadoLayout.createSequentialGroup()
                                .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel_1Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(tel_2Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel_3Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanelEditarContatoSelecionadoLayout.setVerticalGroup(
            jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarContatoSelecionadoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditarContatoSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel_1Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel_3Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel_2Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(observcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar1))
        );

        jPanelEditarContato.add(jPanelEditarContatoSelecionado, "editarContatoSelecionado");

        jPanelPrincipal.add(jPanelEditarContato, "editarContato");

        jPanelListarContatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar Contatos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, contatoList, jTableContatos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tel1}"));
        columnBinding.setColumnName("Tel1");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tel2}"));
        columnBinding.setColumnName("Tel2");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tel3}"));
        columnBinding.setColumnName("Tel3");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableContatos);

        javax.swing.GroupLayout jPanelListarContatosLayout = new javax.swing.GroupLayout(jPanelListarContatos);
        jPanelListarContatos.setLayout(jPanelListarContatosLayout);
        jPanelListarContatosLayout.setHorizontalGroup(
            jPanelListarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelListarContatosLayout.setVerticalGroup(
            jPanelListarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarContatosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelListarContatos, "listarContatos");

        jPanelExcluirContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N

        DefaultListModel listaExcluir = new DefaultListModel();
        List<Contato> listaContatos = FachadaSistema.getInstance().listarContatos();
        for(Contato contatoExcluir: listaContatos){
            listaExcluir.addElement(contatoExcluir.getNome());
        }
        jListExcluir.setModel(listaExcluir);
        jScrollPane4.setViewportView(jListExcluir);

        jButton7.setText("Excluir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelExibirContatosExcluirLayout = new javax.swing.GroupLayout(jPanelExibirContatosExcluir);
        jPanelExibirContatosExcluir.setLayout(jPanelExibirContatosExcluirLayout);
        jPanelExibirContatosExcluirLayout.setHorizontalGroup(
            jPanelExibirContatosExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirContatosExcluirLayout.createSequentialGroup()
                .addGroup(jPanelExibirContatosExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExibirContatosExcluirLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelExibirContatosExcluirLayout.setVerticalGroup(
            jPanelExibirContatosExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirContatosExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelExcluirContatoLayout = new javax.swing.GroupLayout(jPanelExcluirContato);
        jPanelExcluirContato.setLayout(jPanelExcluirContatoLayout);
        jPanelExcluirContatoLayout.setHorizontalGroup(
            jPanelExcluirContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExcluirContatoLayout.createSequentialGroup()
                .addComponent(jPanelExibirContatosExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelExcluirContatoLayout.setVerticalGroup(
            jPanelExcluirContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelExcluirContatoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelExibirContatosExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelPrincipal.add(jPanelExcluirContato, "excluirContato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanelListarContatos.revalidate();
        jPanelListarContatos.repaint();
        mostrarTela("listarContatos");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        Contato contato = new Contato();
        contato.setNome(nome.getText());
        contato.setTelefone1(Integer.parseInt(tel_1.getText()));
        contato.setTelefone2(Integer.parseInt(tel_2.getText()));
        contato.setTelefone3(Integer.parseInt(tel_3.getText()));
        contato.setEmail(email.getText());
        contato.setObservacoes(observcoes.getText());
        FachadaSistema.getInstance().adicionarContato(new Validacoes().validarContato(contato));
        JOptionPane.showMessageDialog(null, "Contato adicionado!");
    }//GEN-LAST:event_salvarActionPerformed

    private void observcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observcoesActionPerformed

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        // TODO add your handling code here:
        if(nome.getText() == null){
            JOptionPane.showMessageDialog(null, "O campo nome deve ser preenchido");
        }
    }//GEN-LAST:event_nomeFocusLost

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mostrarTela("cadastrarContato");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mostrarTela("editarContato");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanelExcluirContato.revalidate();
        jPanelExcluirContato.repaint();
        mostrarTela("excluirContato");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nomeEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEditarActionPerformed

    private void nomeEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeEditarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEditarFocusLost

    private void observcoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observcoes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observcoes1ActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed
        Contato contatoSelecionado = FachadaSistema.getInstance().buscarContatoSelecionadoPorNome(jListEditar.getSelectedValue().toString());
        Contato contatoAlterar = new Contato();
        
        contatoAlterar.setId(contatoSelecionado.getId());
        contatoAlterar.setNome(nomeEditar.getText());
        contatoAlterar.setEmail(emailEditar.getText());
        contatoAlterar.setTelefone1(Integer.parseInt(tel_1Editar.getText()));
        contatoAlterar.setTelefone2(Integer.parseInt(tel_2Editar.getText()));
        contatoAlterar.setTelefone3(Integer.parseInt(tel_3Editar.getText()));
        contatoAlterar.setObservacoes(observcoes1.getText());
        
        FachadaSistema.getInstance().alterarContato(contatoAlterar);
        
        JOptionPane.showMessageDialog(null, "Contato Alterado com Sucesso!");
        jPanelEditarContato.revalidate();
        jPanelEditarContato.repaint();
        
    }//GEN-LAST:event_salvar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Contato contatoSelecionado = FachadaSistema.getInstance().buscarContatoSelecionadoPorNome(jListEditar.getSelectedValue().toString());
        nomeEditar.setText(contatoSelecionado.getNome());
        tel_1Editar.setText(String.valueOf(contatoSelecionado.getTelefone1()));
        tel_2Editar.setText(String.valueOf(contatoSelecionado.getTelefone2()));
        tel_3Editar.setText(String.valueOf(contatoSelecionado.getTelefone3()));
        emailEditar.setText(contatoSelecionado.getEmail());
        observcoes1.setText(contatoSelecionado.getObservacoes());
        mostrarTelaEditar("editarContatoSelecionado");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(null != jListExcluir.getSelectedValue()){
            if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir: "+jListExcluir.getSelectedValue()) == 0){
                FachadaSistema.getInstance().excluirContatoPorNome(jListExcluir.getSelectedValue().toString());
                jPanelExcluirContato.revalidate();
                jPanelExcluirContato.repaint();

                DefaultListModel listaExcluir = new DefaultListModel();
                List<Contato> listaContatos = FachadaSistema.getInstance().listarContatos();
                for(Contato contatoExcluir: listaContatos){
                    listaExcluir.addElement(contatoExcluir.getNome());
                }
                jListExcluir.setModel(listaExcluir);
                JOptionPane.showMessageDialog(null,"Contato excluido com sucesso");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Escolha o contato que você deseja excluir");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<apresentacao.Contato> contatoList;
    private java.util.List<apresentacao.Contato> contatoList1;
    private java.util.List<apresentacao.Contato> contatoList2;
    private java.util.List<apresentacao.Contato> contatoList3;
    private javax.persistence.Query contatoQuery;
    private javax.persistence.Query contatoQuery1;
    private javax.persistence.Query contatoQuery2;
    private javax.persistence.Query contatoQuery3;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailEditar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBanner;
    private javax.swing.JList jListEditar;
    private javax.swing.JList jListExcluir;
    private javax.swing.JPanel jPanelBanner;
    private javax.swing.JPanel jPanelCadastrarContato;
    private javax.swing.JPanel jPanelEditarContato;
    private javax.swing.JPanel jPanelEditarContatoSelecionado;
    private javax.swing.JPanel jPanelExcluirContato;
    private javax.swing.JPanel jPanelExibirContatosBuscaEditar;
    private javax.swing.JPanel jPanelExibirContatosExcluir;
    private javax.swing.JPanel jPanelListarContatos;
    private javax.swing.JPanel jPanelMenuLateral;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableContatos;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeEditar;
    private javax.swing.JTextField observcoes;
    private javax.swing.JTextField observcoes1;
    private javax.swing.JButton salvar;
    private javax.swing.JButton salvar1;
    private javax.swing.JTextField tel_1;
    private javax.swing.JTextField tel_1Editar;
    private javax.swing.JTextField tel_2;
    private javax.swing.JTextField tel_2Editar;
    private javax.swing.JTextField tel_3;
    private javax.swing.JTextField tel_3Editar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
